### ISSUE TITLE
Incorrect url

### ISSUE THREAD

**Issue by wandadotdev** [btholt/complete-intro-to-react-v7#4]
URL `[state of the project up until now: 11-context](https://github.com/btholt/citr-v7-project/tree/master/12-context)` is incorrect. Should be `11-context`

[complete-intro-to-react-v7](https://github.com/btholt/complete-intro-to-react-v7)/[lessons](https://github.com/btholt/complete-intro-to-react-v7/tree/main/lessons)/[06-special-case-react-tools](https://github.com/btholt/complete-intro-to-react-v7/tree/main/lessons/06-special-case-react-tools)/B-context.md

**Comment by btholt** [comment]
thank you!
